import { blackCard, card } from "./card";

export const blackCards = [
  "___? Tem um aplicativo para isso.",
  "Por que não consigo dormir à noite?",
  "Que cheiro é esse?",
  "Eu tenho 99 problemas mas ___ não é um.",
  "Quem roubou biscoitos do pote de biscoitos?",
  "Qual o  próximo brinde do McLanche Feliz?",
  "Antropólogos recentemente descobriram uma antiga tribo que venerava ___",
  "É uma pena que crianças hoje em dia estejam todas se envolvendo com ___",
  "Durante o Período Marrom de Picasso ele pintou centenas de quadros de  ___",
  "A medicina alternativa está adotando os poderes curativos de ___",
  "O Óscar de ___ vai para ___",
  "Passarinho, que som é esse?",
  "O que fez meu último relacionamento acabar?",
  "A nova temporada de A Fazenda apresenta 17 celebridades falidas convivendo com ___",
  "Eu bebo para esquecer ___",
  "Desculpe, professor, não consegui terminar minha tarefa de casa por causa de___",
  "Qual o prazer secreto do Batman?",
  "É assim que o mundo acaba: não com uma explosão, mas com ___",
  "Qual o melhor amigo das garotas?",
  "As novas regras de seguranca agora proíbem ___ em aviões.",
  "___. É assim que eu morro.",
  "Para meu próximo truque, eu  vou tirar  ___ de ___",
  "No novo filme da Xuxa, ela precisa lidar com  ___  pela primeira vez",
  "___  , uma porta de entrada para  ___",
  "O que Aécio Neves prefere?",
  "Queria não ter perdido o manual de ___.",
  "Ao invés de carvão, agora o Papai Noel dá ___ para crianças mal comportadas.",
  "O que é o mais emo?",
  "Em 1000 anos, quando dinheiro impresso for uma memória distante, ___ vai ser a moeda de troca.",
  "Qual a próxima dupla de super-herói/ajudante?",
  "No novo episódio de Black Mirror, Wagner Moura descobre que ___ era, na verdade, ___ o tempo todo.",
  "Um jantar romântico à luz de velas estaria incompleto sem ___.",
  "____ . Aposto que você não consegue ficar sem repetir!",
  "Gente branca gosta de  ___.",
  "____. Toca aqui, mano!",
  "O próximo livro de  J.K Rowling : Harry Potter e ___.",
  "A TOPTHERM TRAZ PRA VOCÊ O LEGÍTIMO ___.",
  "Num mundo devastado por  ___, nosso único consolo é ___.",
  "Guerra! Para que serve?",
  "Durante o sexo eu gosto de pensar em ___.",
  "O que os meus pais escondem de mim?",
  "O que sempre fará você conseguir uma transa?",
  "Quando eu estiver na prisão, eu vou  contrabandear  ___ .",
  "O que eu trouxe do Paraguai?",
  "O que você não gostaria de encontrar na sua comida chinesa?",
  "O que eu vou trazer do passado para provar que sou um feiticeiro poderoso?",
  "Como estou mantendo meu status de relacionamento?",
  "____. É uma cilada, Bino!",
  "Nos teatros mais próximos, ___: O musical.",
  "Enquanto os EUA e a URSS faziam a corrida espacial, o governo brasileiro gastou milhões de reais pesquisando ___",
  "Após os desastres de Mariana, Claudia Raia comprou ___ para o povo mineiro.",
  "Depois de um fiasco no setor de relacoes publicas, o Carrefour nao oferta mais ___",
  "Em sua nova comédia de verão, Renato Aragão é ___ preso no corpo de ___",
  "Os rumores dizem que o prato predileto de Dilma Rousseff é ___ cheio de ___",
  "Mas antes de matá-lo, Sr. Bond, preciso te mostrar ___ ",
  "O que me dá gases incontroláveis?",
  "Como as pessoas idosas cheiram?",
  "A viagem de campo foi arruinada por ___",
  "Quando o Faraó estava imóvel, Moisés chamou pela Praga de ___",
  "Qual o meu poder secreto?",
  "O que tem em toneladas no paraíso?",
  "O que a vovó acharia perturbador, porém estranhamente encantador?",
  "Eu nunca entendi verdadeiramente ___ até encontrar ___",
  "A Polícia Militar comecou a enviar ___ para as crianças em Mãe Luiza.",
  "O que ajuda o Temer a relaxar?",
  "O que o Leo Stronda comeu no jantar?",
  "___ : Bom até a última gota.",
  "Por que eu estou preguento?",
  "O que fica melhor com a idade?",
  "____ : Testado por crianças, aprovado pelas mães.",
  "O que é o mais idiota?",
  "O que o Prouni esta usando para incentivar estudantes do interior a tentar a universidade?",
  "Estudos mostram que ratos de laboratório atravessam labirintos 50% mais rápido depois de expostos a ___",
  "A vida era difícil para os homens das cavernas antes de ___",
  "Escreva um Haikai",
  "Eu não sei que armas vao usar na terceira guerra mundial, mas na quarta usarão ___ ",
  "Por que eu estou todo dolorido?",
  "O que eu estou emprestando?",
  "Nos ultimos momentos de Raul Seixas, ele pensou sobre ___",
  "Numa tentativa de obter maior audiência, o Museu Câmara Cascudo oferecerá uma exibição interativa de  ___",
  "Quando eu for presidente da república, vou criar o ministério de ___",
  "A sessão da tarde apresenta: ___, uma história de ___",
  "Quando eu for um bilionário, vou erguer uma estátua de 20 metros em homenagem a ___",
  "Quando eu estava viajando com LSD, ___ virou ____",
  "Verdade, eu matei ____ . Como? ____",
  "Qual o meu anti-drogas?",
  "___ + ___ = ___",
  "O que nunca falha em animar a festa?",
  "Qual a nova dieta do momento?",
  "A FIFA baniu ___ por dar aos jogadores uma enorme vantagem",
  "Como eu perdi minha virgindade?",
  "Talvez ela tenha nascido assim, talvez seja ___",
  "Eu consigo seguir em frente com uma pequena ajuda de ___ ",
  "Querida tia Tereza, estou tendo um problema com ___ e gostaria da sua ajuda.",
  "Mais uma noite chega, e com ela ___",
  "Disseram que nós éramos loucos, disseram que não poderíamos colocar ___ dentro de ___. Eles estavam errados. ",
  "Papai, por que a mamãe está chorando?",
  "Aqui também é ___",
  "Olha como ela é ___, dá ___ pra ela !",
  'O tema para o próximo Quem Sabe Canta, do Raul Gil, será "Nós somos ___"',
  "Ninguém espera a revolução comunista, nossas principais armas são medo, surpresa e ___ ",
  "A TAM pede desculpas pelo atraso dos voos devido a ___",
  "A seguir, em Esporte Espetacular, o Campeonato Mundial de ___",
  '"Hoje, em Casos de Família: "Socorro! Meu filho é ___ !"',
  "A vida dos povos indígenas no Brasil mudou para sempre quando o homem branco os introduziu a ___",
  "Dica divertida! Quando o seu homem pedir para você fazer um oral, surpreenda-o com ___, no lugar",
  '"Hoje, na Sessão da Tarde: ___, a história de ___"',
  "___. É por isso que as mães vão para o Acre",
  "Eu não acredito que ___ inventou ___",
  "A nova sensação do Funk é o Mc ___",
  "O Yudi girou a roleta do Bom Dia e Cia, e ao invés de vir um play station, veio ___",
  "Beijinho no ombro pra ___ passar longe",
  "Tu tá metida com ___, Morena?",
  "Após a Época do Café, o Brasil investiu na exportação de ___",
  "Casar, foder, matar.",
].map(card).map(blackCard);
