import { card, whiteCard } from "./card";

export const whiteCards = [
  "Português",
  "Abortos com cabide",
  "Carne humana",
  "Autocanibalismo",
  "Mãos de Jazz vigorosas",
  "Passaros que não voam",
  "Fotos de peitos",
  "A coisa certa a se fazer",
  "Acidentes de caça",
  "Um camelo cartunesco apreciando o suave e refrescante gosto de um cigarro",
  "A violação dos nossos direitos humanos fundamentais",
  "Viagra",
  "Autoaversão",
  "Um abdomem espetacular",
  "Um policial honesto com nada a perder",
  "Abstinencia",
  "Um café da manhã balanceado",
  "Red Bull",
  "O ato de esconder uma ereção",
  "Sedativos",
  "Faustão convulsivamente vomitando enquanto uma ninhada de aranhas-caranguejo eclodem em seu cérebro e irrompem de seus ductos lacrimais",
  "O ato de tuitar",
  "O Big Bang",
  "Pessoas com membros amputados",
  "Zumbi dos Palmares",
  "Ex-presidente Lula",
  "Marginalizado",
  "Smegma",
  "O ato de botar um ovo",
  "Carinho",
  "Médici costurando casaquinhos de lã para cães de rua",
  "O papa",
  "Um cu alvejado",
  "Carne de cavalo",
  "Piercings genitais",
  "Dedadas",
  "Asiáticos idosos",
  "Perigo estranho",
  "O próprio medo",
  "Ciência",
  "Cura Gay",
  "Patinação de casais do mesmo sexo",
  "Os terroristas",
  "Sexo com ela",
  "Pornochanchada",
  "Bulimia",
  "Apagamento de etnias",
  "Trapaça nas paraolimpíadas",
  "Restart",
  "Heteronormatividade",
  "Regina Casé",
  "Biquinho",
  "Motosserras como mãos",
  "Placenta",
  "Os muito deficientes",
  "Antônio Fagundes voando num boi feito de raios",
  "Inês Brasil",
  "FADAS !",
  "Lobotomia com picador de gelo",
  "Thais Araújo",
  "Injeções de hormônios",
  "Um Urubu com chapéu de palha",
  "Prepúcio",
  "Morte",
  "Dublês",
  "A mão invisível",
  "Plugs anais",
  "Um chapéu muito maneiro",
  "Enchentes",
  "Camisinhas saborizadas",
  "Morte por disenteria",
  "Lutas de travesseiros sexy",
  "Tratado de Tordesilhas",
  "Uma punheta triste",
  "Homens",
  "Exclusão social",
  "Pitty",
  "Orfãos apaixonantes",
  "Surf",
  "O clitóris",
  "Cangaceiros",
  "Amigos que comem o lanche todo",
  "O metrô",
  "Fingir que se importa",
  "Ataques de dinossauros",
  "Um micropênis",
  "Uma maldicao indígena",
  "Agricultura",
  "Jóias",
  "Uma coçada clandestina na bunda",
  "O sul",
  "Cheirar cola",
  "Contatinhos",
  "Meus quadris",
  "Gansos",
  "Babaquice com crianças",
  "Estraga prazeres",
  "Luz do sol e arco-iris",
  "PARA NOSSA ALEGRIA !",
  "Destruicao mutuamente assegurada",
  "Os pelos do peito de Tony Ramos",
  "Sexting",
  "Complexo de Edipo",
  "AAAAAAAAAAAAAAAAAAAAAAAAAA",
  "Um festival de salsicha",
  "Roberto Carlos",
  "A Cuca",
  "Cavalheirismo",
  "Compartilhar de seringas",
  "Riqueza",
  "Tapado",
  "O Leão do Proerd",
  "Combustão espontânea",
  "Faculdade",
  "Necrofilia",
  "A seleção chinesa de ginástica",
  "Aquecimento global",
  "Peidar e sair de fininho",
  "O Mau correndo pelos encanamentos da Assembléia de Deus",
  "Um galo com papete",
  "Inveja peniana",
  "Liberdade pessoal",
  "Gente branca",
  "Eduardo Cunha",
  "Um voicemail bizarro",
  "Fermento",
  "Seleção natural",
  "Masturbação",
  "Bolinhos Bauducco",
  "Festa junina",
  "Polegares opositores",
  "Um capuccino grande, sem açúcar, gelado e com caramelo de soja",
  "Sujar-se",
  "Uma mulher negra audaciosa",
  "Lontras com meias de bolinhas e nariz de palhaço",
  "O ensino de emoções a um robô",
  "A Rita Lee vestida de banana",
  "Um tiroteio",
  "Chicoteio",
  "Sexo de pandas",
  "Catapultas",
  "Lázaro Ramos",
  "O pênis do Alexandre Pires",
  "32 cm",
  "Minas terrestres",
  "Um mar de problemas",
  "Acarajé no café da manhã",
  "Nazaré Tedesco segurando uma tesoura",
  "Fricção",
  "Bolas",
  "AIDS",
  "O KKK",
  "Pudim",
  "Seppuku",
  "É o Tchan",
  "Gandhi",
  "Paralamas do Sucesso",
  "Preadolescentes",
  "A minoria simbólica",
  "Amigos com beneficios",
  "Presentes",
  "Bukkake pixelado",
  "Professores substitutos",
  "Treta",
  "Uma detonacao termonuclear",
  "Sono durante uma aula chata",
  "#EuEscolhiEsperar",
  "Um cavalinho",
  "Vergonha na cara",
  "Cáries dentais",
  "Pastel de queijo e caldo de cana",
  "Cheiro de gente velha",
  "Lampião",
  "Cozinha mexicana autentica",
  "Pirulitos Gigantes",
  "Louro José",
  "Palmirinha vestida de paquita",
  "Mulheres fortes",
  "Intervenção Militar",
  "Topless",
  "Meritocracia",
  "Bacteria comedora de carne",
  "Abuso infantil",
  "Um freezer cheio de órgãos",
  "Um momento de silêncio",
  "Sandy e Junior",
  "Sonhos eróticos com o Abaporu",
  "Robocop",
  "Aquele teletubbie gay",
  "Doce, doce vinganca",
  "Banquete chique",
  "Uma colonoscopia com suas próprias fezes todos os dias",
  "O chupacu",
  "Fraternidades judias",
  "Roupa intima comestivel",
  "Gente pobre",
  "Rodízio de pizza por dez reais",
  "Anitta aos 65 anos",
  "Aquela coisa que eletrocutou seu abdomem",
  "A insensatez humana",
  "Bosta ardente",
  "Cards Against Humanity",
  "Um assassinato muito cruel",
  "Tempo pra mim",
  "A morte inevitavel do universo",
  "Emissões noturnas",
  "Problemas com pai",
  "Os médicos cubanos",
  "Bruna Marquezine",
  "Sexo no banheiro do Mc Donalds",
  "Laminas de mamilos",
  "Calças sem bunda",
  "Nudez frontal completa",
  "Kleber Bambam",
  "Passiva-agressividade",
  "Dilma Rousseff",
  "Atropelamento",
  "Menstruação",
  "Coito interrompido",
  "Garotas em clínicas de aborto",
  "Ditadura Gay",
  "A Biblia Sagrada",
  "Paz mundial",
  "Morte aos seus inimigos esmagados por um candelabro ",
  "Torção testicular",
  "O leiteiro",
  "Um paradoxo temporal",
  "Hot Pockets",
  "Caras que não ligam",
  "Churrasco de mico-leão-dourado",
  "Darth Vader",
  "Conexão humana genuína",
  "Sem-Teto",
  "O cu imaculado de Eliana",
  "Gloryholes",
  "Solos de saxofone",
  "A arte da sedução",
  "Deus",
  "Design inteligente",
  "Um sistema de classes impregnado",
  "Fogo amigo",
  "Emoções",
  "Eugenia",
  "Uma boa cheirada",
  "Uma bola de cera de ouvido, semen e pedaços de unha",
  "Um tamagotchi rejeitado",
  "Estupidez imensurável",
  "Migalhas espalhadas por todo o maldito tapete",
  "O coracao de uma crianca",
  "Sedução",
  "O gosto refrescante e geladinho do Guaraná Antartica",
  "O cu delicioso do Caio Castro",
  "Uma surpresa salgada",
  "Piadas sobre o Holocausto em uma hora ruim",
  "Minha alma",
  "Minha vida sexual",
  "Ovos de pterodactilos",
  "Seu Coiso, Coisa e Coisinha (ilha Ra-Tim-Bum)",
  "Qualquer coisa que saia da boca de Rachel Sheherazade",
  "72 virgens",
  "Epidemia de varíola",
  "Pedofilos",
  "Um tapa merecido",
  "Uma tartaruga mordendo a ponta do seu penis",
  "Uma vaca louca",
  "Um pum engraçado",
  "Minha colecao de objetos sexuais high-tech",
  "Um homem de meia idade de patins",
  "O sangue de Cristo",
  "Preliminares meia-boca",
  "Amostras grátis",
  "Babacas em seus Iphones",
  "Stalin",
  "12 GB de gifs da Gretchen em HD",
  "Coxinhas",
  "O teto de vidro",
  "Uma boca suja",
  "Diversão em uma piscina de lágrimas de crianças",
  "Fritação",
  "Os deformados",
  "Os braços de Marcela Temer",
  "Explosões",
  "Dandara dos Palmares",
  "Michel Temer",
  "Bolsonaro",
  "Atitude",
  "Essa resposta é pós-moderna",
  "Capitalismo",
  "Morte por falta de ar perto do nariz do Luciano Huck",
  "Exercícios de construção de times",
  "Repressão",
  "Comunismo",
  "Uma bolsa de feijões mágicos",
  "Uma espanhola assimétrica",
  "Pais mortos",
  "Ridicularização em público",
  "Exibição de acasalamento",
  "Um mímico tendo um AVC",
  "Stephen Hawking falando safadezas",
  "Criancas africanas",
  "Herpes bucal",
  "Uma vovó pelada",
  "Destruição da evidência",
  "Putas",
  "Italianos",
  "Um milhão de reais em barras de ouro, que valem mais do que dinheiro",
  "Um moinho de vento cheio de cadáveres",
  "Sua alteza, rainha Elizabeth II",
  "Exatamente o que você esperava",
  "Uma corrente interminável de diarréia",
  "Problemas de classe média",
  "Torrada",
  "Uma camisinha defeituosa",
  "Doação de pedra do rim",
  "Lepra",
  "Um tumor cerebral",
  "Abelhas ?",
  "Cachorrinhos !",
  "Brigas de galo",
  "Sangue, fadiga, lágrimas e suor",
  "Esperanca",
  "Cu no lugar de olhos",
  "Incesto",
  "Roubo de túmulo",
  "Asiaticos que não são bons com matematica",
  "Alcoolismo",
  "Disfunção erétil",
  "Felipe Dylon",
  "Os Judeus",
  "Bestialidade",
  "Crushes",
  "Testemulhas de Jeová",
  "Crianças com câncer de bunda",
  "Três pintos ao mesmo tempo",
  "Auschwitz",
  "Sopa quente demais",
  "Yodeleio inapropriado",
  "Bomba de hormônios",
  "Uma AK-47",
  "Uma cara feia",
  "Uma vagina com joias",
  "A ira de Vladimir Putin",
  "O próprio demônio",
  "Meu status de relacionamento",
  "Uma maldita paz e quietude",
  "Fabulosidade",
  "Lactacao",
  "Sexo oral não-reciproco",
  "Minha ex",
  "Meus genitais",
  "Uma vagina cibernética que faz torrada e tem wifi",
  "Orgasmo feminino",
  "Um irlandês sóbrio que não se importa com batatas",
  "Reabilitação por ordem judicial",
  "O parto do anticristo",
  "Os gays",
  "Ecstasy",
  "Estrogenio",
  "Brutalidade policial",
  "Travestis passaveis",
  "Pessoas sem pele",
  "Um homem quase gozando",
  "Dedos em formato de penis",
  "Racismo",
  "Racismo reverso",
  "Sexo surpresa !",
  "Sutilezas classistas",
  "Os tweets do Neymar Jr.",
  "Musicas atuais",
  "Seu irmão estranho",
  "Uma vida de tristezas",
  "Calças extremamente apertadas",
  "Fraldas sujas",
  "Casamento, procriação, seguida de fotos, aposentadoria e morte",
  "Pornô de tentaculos",
  "O boi tatá",
  "Muito gel de cabelo",
  "Células-tronco embrionárias",
  "Forças misteriosas fora do nosso controle",
  "Ira menstrual",
  "Os ritmos africanos",
  "Acidentes horríveis de depilação a laser",
  "Objetos brilhantes",
  "Golden showers",
  "Meus demônios interiores",
  "Roubo de doces de crianças órfãs",
  "Um homem branco numa van",
  "Gravidez na adolescência",
  "Um mongolóide robusto",
  "Nazistas",
  "Privilégio branco",
  "Uma ereção que dura mais de quatro horas",
  "Uma festa de aniversario desapontadora",
  "Puberdade",
  "Dois anões cagando num balde",
  "Deveres de esposa",
  "O fruto proibido",
  "Raul Gil alisando a própria barriga até dormir",
  "Tensão sexual",
  "A separação do Calypso",
  "Um antílope com gases",
  "Aquelas vezes que voce fica com areia na sua vagina",
  "Um louco que vive numa caixa e sequestra mulheres",
  "Tartarugas de assalto com bafo ácido biologicamente modificadas",
  "O fim dos dias",
  "Estrelas pornô",
  "Um feto",
  "Obesidade",
  "Quando voce peida e um pouquinho sai",
  "Oompa-Loompas",
  "BATMAN!!!",
  "Gente negra",
  "A luz de um bilhão de sóis",
  "Gente gostosa",
  "Vovó",
  "Sacrifício de uma virgem",
  "Trilha de Lágrimas",
  "Fome",
  "Pintura a dedo",
  "O milagre do nascimento",
  "Cabras comendo latas",
  "Um macaco fumando",
  "Cura pela fé",
  "Sexo menstrual",
  "Bebês mortos",
  "Evangélicos ultraconservadores",
  "Impotência",
  "Concursos de beleza infantis",
  "Centauros",
  "Desodorante AXE",
  "Wesley Safadão",
  "O direito a voto feminino",
  "Crianças com coleiras",
  "Pornografia de Harry Potter",
  "A dança da fada da ameixa doce",
  "O dedo perdido do Lula",
  "Arremesso de anões",
  "Pessoas de exatas",
  "Almoço",
  "Mulheres em comerciais de iogurte",
  "Fernandinho Beira-Mar",
  "Coxas poderosas",
  "O Dollynho, bem atrás de você",
  "Ferimentos de facadas multiplas",
  "Melhorias ciberneticas",
  "Servidão",
  "Outro maldito filme de vampiro",
  "A Ana Maria Braga dançando Ragatanga de biquini fio-dental de estampa de oncinha",
  "Uma grande comoção por motivo nenhum",
  "Um pouquinho de mijo",
  "A agitação",
  "Fantasmas",
  "Bananas de Pijamas",
  "Escuta ativa",
  "Vômito de ar",
  "Pilotos kamikaze",
  "A Força",
  "Vibradores azuis",
  "Criança Esperança",
  "Pessoas de Humanas",
  "Aplausos ao sol",
  "Heterossexuais",
  "Rebuceteio",
  "Péssimas escolhas de vida ",
  "Pessoas pobres",
  "Pessoas ricas",
  "Minha vagina",
  "Personagens femininas fortes",
  "Sexo consensual",
  "Um balde de cabeças de peixes",
  "Um coração de uma criança",
  "A vida de um pirata",
  "Crucificação",
  "Cinco litros de cachaça",
  "O ursinho Pooh possuído pelo demônio",
  "Um bangalô na praia",
  "Uma capivara bebê usando pantufinhas e pijaminha azul",
  "Empregos",
  "400 anos de atrocidades coloniais",
  "Pessoas indígenas",
  "Uma bela xícara de café",
  "Uma tribo de mulheres guerreiras",
  "Rolezeira",
  "Memes",
  "Trenzinho Carreta Furacão",
  "Silvio Santos jogando dez aviõezinhos de 100 reais",
  "Uma manchete de notícia do Ego",
  "As bailarinas do Faustão",
  "A Maisa tirando a peruca do Silvio Santos",
  "A Glória Maria doidona na Jamaica",
  "Apropriação cultural",
  "Um cachorro quente de rua com recheio de procedência duvidável",
].map(card).map(whiteCard);
